### ISSUE TITLE
How to change the code block font size?

### ISSUE THREAD

**Issue by AurevoirXavier** [lampsitter/egui_commonmark#26]
Is looks like `TextStyle::Monospace` doesn't affect that part.

**Comment by AurevoirXavier** [comment]
<img width="630" alt="image" src="https://github.com/lampsitter/egui_commonmark/assets/16152305/472b99ac-ee54-4445-8345-65fb89b0f65f">
I don't know why does the code size is always smaller then the normal text.

**Comment by lampsitter** [comment]
Interesting. By default egui_extras is used for syntax highlighting and it appears that it has hardcoded the monospace font to [10!](https://github.com/emilk/egui/blob/963be247f26f2ddd72c03649e9ebc0ec88ac8431/crates/egui_extras/src/syntax_highlighting.rs#L216C15-L216C15)

It should work correctly with the `better_syntax_highlighting` feature enabled.

Side note: I recommend to use the default font as a fallback font, so that the copy button in the code block will be displayed with the correct icon instead of the `?`. I _think_ the proportional font is used for that.

**Comment by lampsitter** [comment]
Looks like there is an issue for this already. https://github.com/emilk/egui/issues/3549

**Comment by AurevoirXavier** [comment]
> Interesting. By default egui_extras is used for syntax highlighting and it appears that it has hardcoded the monospace font to [10!](https://github.com/emilk/egui/blob/963be247f26f2ddd72c03649e9ebc0ec88ac8431/crates/egui_extras/src/syntax_highlighting.rs#L216C15-L216C15)
> 
> It should work correctly with the `better_syntax_highlighting` feature enabled.
> 
> Side note: I recommend to use the default font as a fallback font, so that the copy button in the code block will be displayed with the correct icon instead of the `?`. I _think_ the proportional font is used for that.

I don't think this is an issue with this crate. By the way, how do I set the fallback font?

**Comment by lampsitter** [comment]
Should be fixed in the next egui version https://github.com/emilk/egui/pull/5090
