### ISSUE TITLE
Table creates extra columns for items that belong in the same column

### ISSUE THREAD

**Issue by crumblingstatue** [lampsitter/egui_commonmark#33]
```markdown
column a   | column b
-----------|----------
item 1     | item 2
`item` `3` | item 4
```
This should be rendered as
![image](https://github.com/lampsitter/egui_commonmark/assets/1521976/092b032f-6ed0-4ecd-8537-fe52768070be)

With egui_commonmark, it's rendered as
![image](https://github.com/lampsitter/egui_commonmark/assets/1521976/abdc310a-6623-4cb4-b0f1-5a3ad69dd9ac)

**Comment by lampsitter** [comment]
The problem is that `egui::Grid` is used, which creates a new column for each widget. egui_commonmark creates multiple widgets per column which is why it messes up. It might take a while to figure out the best solution to this. I have tried with egui_extras::Table, but it is really difficult to use in this architecture.
